name: LVEwoldts
favicon: null
layout_spectrum: 0.65499
typography_spectrum: 0.07377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfbe2'
    - '#bb9f78'
    - '#452018'
    - '#67553d'
    - '#d7cdc4'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
